# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hedger',
                'doc_host': 'https://fleclerc.github.io',
                'git_url': 'https://github.com/fleclerc/hedger',
                'lib_path': 'hedger'},
  'syms': {'hedger.core': {'hedger.core.foo': ('core.html#foo', 'hedger/core.py')}}}
