# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00-hedgerprep.ipynb.

# %% auto 0
__all__ = ['directory', 'pattern']

# %% ../nbs/00-hedgerprep.ipynb 1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot
from fastai.tabular.all import *


# %% ../nbs/00-hedgerprep.ipynb 5
from pathlib import Path

# Define the directory and pattern
directory = Path("./market")
pattern = "*mbp-10*"

# Iterate over files matching the pattern
for file_path in directory.glob(pattern):
    print(file_path)

    # Extract the date from the file name
    date_str = file_path.name[10:18]
    print(f"Extracted date: {date_str}")
